# -*- coding: utf-8 -*-
"""Group6_March_Break_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FCCpq1qRizFbtvelHuNDjfQWrYlmmQCZ

###📌 Welcome to the T-CAIREM, March Break Model Training & Evaluation Notebook!


👋 Welcome to the March Break T-CAIREM Coding Challenge! Our goal is to predict massive hemorrhage protocol (MHPs). If this model works, we could implement the model in our hospital to automate the prediction of MHPs, potentially improving the speed of activation, accuracy of activation, and efficiency of resource allocation.

**In this notebook, we will:**

1️⃣ Pre-process the Data
- Load the dataset
- Identify and remove erroneous values
- Split the data into training & testing sets

2️⃣ Train Machine Learning Models
- Train a Random Forest Classifier using Scikit-learn
- Train an XGBoost Classifier using the XGBoost library
- Tune hyperparameters for better performance

3️⃣ Evaluate Model Performance
- Accuracy, Precision, Recall, F1-Score
- Confusion Matrix & ROC Curve
- Feature Importance Analysis

4️⃣ Explain Model Predictions with SHAP
- Visualize SHAP summary plots to see feature impact
- Use SHAP decision plots to interpret individual predictions


💡 Why is this important?
Understanding how machine learning models work beyond accuracy metrics is crucial. We will use visualization techniques to explain model decisions and assess reliability.


📌 Run each cell sequentially and follow the comments for guidance.


💻 Let's get started! 🚀

💡 📌 To add this section to your Google Colab notebook:
- Create a new text cell in Colab.
- Copy & paste the text above.
- Set the cell to Markdown format (Click on the cell → Change cell type → Markdown).
- Run the cell!
- This will display the introduction in a formatted and structured way.


We are here to help you! Let us know if you want any modifications! 😊

###Part 1 -- Exploring your Dataset

In this section we provide code for how to assess the columns that you have in your dataset. It is important to do this before you develop a model
"""

#Mount drive -- this can be commented out after the drive is imported
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder

#removing warnings for cleaner output
import warnings
warnings.filterwarnings('ignore')

#Import the dataset
df = pd.read_csv("drive/My Drive/T-CAIREM Resources for March Break Trainees/MHP_Dataframe.csv") #Gemma

#Let's check out what the data looks like?
print(df.head())  #This shows the first 5 patients in our dataset

# Check the number of records
num_records = df.shape[0]
print(f"Number of records: {num_records}")

# Check for duplicate records by ID (assuming an 'ID' column exists)
if "ID" in df.columns:
    num_duplicates = df.duplicated(subset=["ID"]).sum()
    print(f"Number of duplicate records by ID: {num_duplicates}")
else:
    print("No 'ID' column found. Cannot check for duplicates by ID.")

# Summarize the maximum and minimum values for numerical columns
numerical_summary = df.describe().T[['min', 'max']]
print("\nNumerical summary (Min/Max values):")
print(numerical_summary)
# When evaluating the print out, we are checking for whether the numbers are logical and make sense (ex. age > 120 would likely be an error in data input)

# Identify column types (categorical vs numerical)
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()
numerical_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()

print("\nCategorical Columns:", categorical_cols)
print("Numerical Columns:", numerical_cols)

# Count the number of missing values per column
missing_values = df.isnull().sum()
print("\nMissing values per column:")
print(missing_values[missing_values > 0])  # Only show columns with missing values
# Note that random forest models can handle missing data, XGBoost cannot

# Decide on features to include in the model
# We exclude the target variable ('dead_on_arrival') and any non-predictive identifiers like 'ID'
excluded_features = ["dead_on_arrival"]  #This is an example of a feature to exlude
features = [col for col in df.columns if col not in excluded_features]

print("\nFeatures selected for the model:")
print(features)

# Consider adding additional code to visualize these summaries!

"""### Part 2 -- Pre-processing your features

To be used by the model, we need to change the structure of the features/variables. This section provides code for how the features need to be modified.

Categorical variables need to be turned into 0/1 and numerical variables need to be scaled. Scaling of numerical values improves model performance.
"""

# 📌 Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from imblearn.over_sampling import SMOTE
from collections import Counter

# 📌 Load dataset
df = pd.read_csv("drive/My Drive/T-CAIREM Resources for March Break Trainees/MHP_Dataframe.csv")

# ✅ **Step 1: Remove Unnecessary Columns**
columns_to_remove = [
    "ID", "Unnamed: 0", "dead_on_arrival", "n_blood_products_4", "n_blood_products_24",
    "n_blood_products_los", "race", "income", "fam_present", "sex"
]
df = df.drop(columns=columns_to_remove, errors="ignore")

# ✅ **Step 2: Exclude Patients with Implausible Values**
valid_ranges = {
    "systolic_bp": (50, 250),
    "diastolic_bp": (30, 150),
    "heart_rate": (30, 250),
    "oxygen_saturation": (50, 100),
    "hemoglobin": (5, 22),
    "platelet_count": (10000, 500000),
    "INR": (0.5, 10),
    "glucose_level": (25, 600),
    "lactate_level": (0.1, 15),
    "temperature": (30, 45),
    "respiratory_rate": (5, 60),
    "shock_index": (0.1, 3),
    "base_excess": (-30, 30),
    "white_blood_count": (1000, 20000),
    "fibrinogen": (50, 1000),
    "blood_urea_nitrogen": (2, 200),
    "creatinine": (0.1, 20)
}

# Apply range filtering
for col, (min_val, max_val) in valid_ranges.items():
    if col in df.columns:
        df = df[(df[col] >= min_val) & (df[col] <= max_val)]  # Keep only valid patients

print(f"✅ Dataset after filtering implausible values: {df.shape}")

# ✅ **Step 3: Remove Patients with Non-Trauma Cases**
df = df[~df["trauma_type"].isin(["Medical", "Unknown"])]

print(f"✅ Dataset after removing non-trauma cases: {df.shape}")

# ✅ **Step 4: Define Target Variable (`MHP_activation`) & Features**
y = df["MHP_activation"]  # Target variable
X = df.drop(columns=["MHP_activation"])  # Features

# ✅ **Step 5: One-Hot Encode Categorical Variables**
categorical_cols = ["trauma_type", "mechanism_of_injury"]
X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

# ✅ **Step 6: Split Data into Training and Testing Sets (80-20 split)**
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# ✅ **Step 7: Handle Missing Values**
X_train = X_train.fillna(X_train.median(numeric_only=True))
X_test = X_test.fillna(X_train.median(numeric_only=True))  # Use train median for consistency

# ✅ **Step 8: Normalize Numerical Features**
numerical_cols = [
    'systolic_bp', 'diastolic_bp', 'heart_rate', 'oxygen_saturation', 'hemoglobin',
    'platelet_count', 'INR', 'glucose_level', 'lactate_level', 'temperature',
    'respiratory_rate', 'shock_index', 'base_excess', 'white_blood_count', 'fibrinogen',
    'blood_urea_nitrogen', 'creatinine'
]

scaler = StandardScaler()
X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])
X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])

# Optional Min-Max Scaling (Uncomment to Use)
# minmax_scaler = MinMaxScaler()
# X_train[numerical_cols] = minmax_scaler.fit_transform(X_train[numerical_cols])
# X_test[numerical_cols] = minmax_scaler.transform(X_test[numerical_cols])

# ✅ **Step 9: Apply SMOTE to Balance the Dataset**
smote = SMOTE(random_state=42)

# Before applying SMOTE, check class distribution
print("🔍 Before SMOTE:", Counter(y_train))

# Apply SMOTE only on the training set
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

# After applying SMOTE, check class distribution
print("✅ After SMOTE:", Counter(y_train_smote))

print("🎯 Preprocessing complete! Ready for model training.")

"""### Part 3 -- Developing your Machine Learning Model

In this section we will train (1) a random forest model and (2) an XGBoost model. We select these two models because the literature has shown that they perform very well with this prediction task. In the machine learning world, it is common to compare multiple models to determine which one best captures the relationships between your features and your outcome variables.
"""

# 📌 Import Libraries
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score, precision_score, recall_score

# ✅ Random Forest Hyperparameter Tuning (Optimized for F1-Score)
rf_params = {
    'n_estimators': [100, 300, 500],  # More trees for better learning
    'max_depth': [10, 20, 30, None],  # Deeper trees can capture complex patterns
    'min_samples_split': [2, 5, 10],  # Prevents overfitting
    'min_samples_leaf': [1, 2, 5],  # Prevents small, overfitted leaves
    'max_features': ['sqrt', 'log2'],  # Feature selection
    'class_weight': ['balanced']  # Helps with imbalanced data
}

rf = RandomForestClassifier(random_state=42, n_jobs=-1)
rf_grid = GridSearchCV(rf, rf_params, cv=5, scoring='f1', n_jobs=-1)  # ✅ Changed to F1-score
rf_grid.fit(X_train_smote, y_train_smote)

# ✅ Get Best RF Model & Predict using threshold tuning
best_rf = rf_grid.best_estimator_
rf_probs = best_rf.predict_proba(X_test)[:, 1]  # Get probabilities
threshold = 0.3  # Adjust threshold for better recall
rf_preds = (rf_probs > threshold).astype(int)

rf_f1 = f1_score(y_test, rf_preds)
rf_recall = recall_score(y_test, rf_preds)
rf_precision = precision_score(y_test, rf_preds)

print(f"🔵 Best Random Forest F1-Score: {rf_f1:.4f}")
print(f"🔵 Best RF Precision: {rf_precision:.4f}")
print(f"🔵 Best RF Recall: {rf_recall:.4f}")
print(f"🔵 Best RF Parameters: {rf_grid.best_params_}")

# ✅ XGBoost Hyperparameter Tuning (Optimized for F1-Score)
xgb_params = {
    'n_estimators': [100, 300, 500],  # More trees = better learning
    'learning_rate': [0.01, 0.05, 0.1, 0.2],  # Lower = slower but better generalization
    'max_depth': [3, 6, 10, 15],  # Deeper trees capture complexity
    'subsample': [0.6, 0.8, 1.0],  # Fraction of data per tree
    'colsample_bytree': [0.6, 0.8, 1.0],  # Fraction of features per tree
    'gamma': [0, 1, 5]  # Regularization
}

xgb = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss', n_jobs=-1)
xgb_grid = GridSearchCV(xgb, xgb_params, cv=5, scoring='f1', n_jobs=-1)  # ✅ Changed to F1-score
xgb_grid.fit(X_train_smote, y_train_smote)

# ✅ Get Best XGBoost Model & Predict using threshold tuning
best_xgb = xgb_grid.best_estimator_
xgb_probs = best_xgb.predict_proba(X_test)[:, 1]  # Get probabilities
xgb_preds = (xgb_probs > threshold).astype(int)

xgb_f = f1_score(y_test, xgb_preds)
xgb_recall = recall_score(y_test, xgb_preds)
xgb_precision = precision_score(y_test, xgb_preds)

print(f"🔴 Best XGBoost F1-Score: {xgb_f1:.4f}")
print(f"🔴 Best XGB Precision: {xgb_precision:.4f}")
print(f"🔴 Best XGB Recall: {xgb_recall:.4f}")
print(f"🔴 Best XGB Parameters: {xgb_grid.best_params_}")

"""### Part 4 -- Evaluating your Machine Learning Model

Now that we have models, let's see how well they work!

When evaluating machine learning models, we need to explore more than just the accuracy of models. Why? Because models can be accurate potentially only because of the prevalence of the outcome.

Another important part of evaluating models, is seeing what features they are using to predict the outcome. This can tell us if our model "makes sense" and it also provides insights that are highly relevant to clinicians.
"""

import shap
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score,
    confusion_matrix, classification_report, roc_curve
)
import seaborn as sns

# Note that in this block, we will evaluate the following metrics for the random forest model and then for the XGBoost model:
# ✅ Accuracy, Precision, Recall, F1-Score (to assess model performance)
# ✅ Confusion Matrix (to visualize classification errors)
# ✅ ROC Curve & AUC Score (to evaluate discrimination ability)
# ✅ Feature Importance (to understand which features impact the model most)
# ✅ SHAP Values & Plots (to explain how individual features contribute to predictions)


### 🚀 Random Forest Evaluation ###

# Generate predictions
rf_preds = best_rf.predict(X_test)
rf_probs = best_rf.predict_proba(X_test)[:, 1]  # Get probability scores for ROC-AUC

# ✅ Compute key evaluation metrics
rf_accuracy = accuracy_score(y_test, rf_preds)  # Proportion of correctly classified cases
rf_precision = precision_score(y_test, rf_preds)  # TP / (TP + FP) - how many positive predictions were correct?
rf_recall = recall_score(y_test, rf_preds)  # TP / (TP + FN) - ability to detect all actual positives
rf_f1 = f1_score(y_test, rf_preds)  # Harmonic mean of precision and recall
rf_auc = roc_auc_score(y_test, rf_probs)  # Measures discrimination ability

# Print metrics
print("🔵 Random Forest Performance:")
print(f"Accuracy: {rf_accuracy:.4f}")
print(f"Precision: {rf_precision:.4f}")
print(f"Recall: {rf_recall:.4f}")
print(f"F1-Score: {rf_f1:.4f}")
print(f"AUC Score: {rf_auc:.4f}")

# ✅ Confusion Matrix - shows actual vs. predicted values
plt.figure(figsize=(6, 5))
sns.heatmap(confusion_matrix(y_test, rf_preds), annot=True, fmt='d', cmap='Blues',
            xticklabels=['No', 'Yes'], yticklabels=['No', 'Yes'])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Random Forest Confusion Matrix")
plt.show()

# ✅ ROC Curve - shows trade-off between sensitivity & specificity
rf_fpr, rf_tpr, _ = roc_curve(y_test, rf_probs)
plt.figure(figsize=(6, 5))
plt.plot(rf_fpr, rf_tpr, label=f"AUC = {rf_auc:.4f}")
plt.plot([0, 1], [0, 1], 'k--')  # Random chance line
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Random Forest ROC Curve")
plt.legend()
plt.show()

# ✅ Feature Importance - Shows which features contribute most to predictions
rf_importances = best_rf.feature_importances_
rf_features = X.columns

plt.figure(figsize=(8, 6))
sns.barplot(x=rf_importances, y=rf_features)
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Random Forest Feature Importance")
plt.show()

# ✅ SHAP Analysis (Explainability of Model Predictions)
explainer_rf = shap.Explainer(best_rf, X_test)
shap_values_rf = explainer_rf(X_test)

# Summary plot - shows overall feature impact
shap.summary_plot(shap_values_rf, X_test)

# SHAP Decision Plot - shows how a sample's feature values affect the prediction
shap.decision_plot(explainer_rf.expected_value[1], shap_values_rf[0], feature_names=X_test.columns)


### 🚀 XGBoost Evaluation ###

# Generate predictions
xgb_preds = best_xgb.predict(X_test)
xgb_probs = best_xgb.predict_proba(X_test)[:, 1]  # Get probability scores for ROC-AUC

# ✅ Compute key evaluation metrics
xgb_accuracy = accuracy_score(y_test, xgb_preds)
xgb_precision = precision_score(y_test, xgb_preds)
xgb_recall = recall_score(y_test, xgb_preds)
xgb_f1 = f1_score(y_test, xgb_preds)
xgb_auc = roc_auc_score(y_test, xgb_probs)

# Print metrics
print("🔴 XGBoost Performance:")
print(f"Accuracy: {xgb_accuracy:.4f}")
print(f"Precision: {xgb_precision:.4f}")
print(f"Recall: {xgb_recall:.4f}")
print(f"F1-Score: {xgb_f1:.4f}")
print(f"AUC Score: {xgb_auc:.4f}")

# ✅ Confusion Matrix
plt.figure(figsize=(6, 5))
sns.heatmap(confusion_matrix(y_test, xgb_preds), annot=True, fmt='d', cmap='Reds',
            xticklabels=['No', 'Yes'], yticklabels=['No', 'Yes'])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("XGBoost Confusion Matrix")
plt.show()

# ✅ ROC Curve
xgb_fpr, xgb_tpr, _ = roc_curve(y_test, xgb_probs)
plt.figure(figsize=(6, 5))
plt.plot(xgb_fpr, xgb_tpr, label=f"AUC = {xgb_auc:.4f}", color='red')
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("XGBoost ROC Curve")
plt.legend()
plt.show()

# ✅ Feature Importance
xgb_importances = best_xgb.feature_importances_
xgb_features = X.columns

plt.figure(figsize=(8, 6))
sns.barplot(x=xgb_importances, y=xgb_features, color='red')
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("XGBoost Feature Importance")
plt.show()

# ✅ SHAP Analysis (Explainability of Model Predictions)
explainer_xgb = shap.Explainer(best_xgb, X_test)
shap_values_xgb = explainer_xgb(X_test)

# Summary plot - shows overall feature impact
shap.summary_plot(shap_values_xgb, X_test)

# SHAP Decision Plot - shows how a sample's feature values affect the prediction
shap.decision_plot(explainer_xgb.expected_value, shap_values_xgb[0], feature_names=X_test.columns)